version: 0.1.0.{build}

image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1

branches:
  only:
  - master

cache:
- packages -> packages.config

test: off

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- nuget update -self
- nuget restore

build:
  project: NFive.SDK.Server.sln
  verbosity: minimal
  publish_nuget: true
